### PR TITLE
Custom commit message for dist-git

### PR DESCRIPTION
**Pull request by dbecvarik**
Added new option `--build-osbs-commit-msg` which you can use to
specify custom commit message for dist-git

### CODE REVIEW

**Comment by dbecvarik** [comment]
fixes #224

**Comment by goldmann** [comment]
Probably a mention in the docs would be useful, WDYT?

**Comment by dbecvarik** [comment]
its mentioned https://github.com/cekit/cekit/pull/299/files#diff-f9476ebc9a3c20aef98265a9b3fe9357R32

**Comment by goldmann** [comment]
Ah, sorry!

**Comment by dbecvarik** [comment]
nps, thanks :)

**Pull request merged**
