### PR TITLE
Migrate to using subprocess.run. Create a run_wrapper around that. Ad…

### PR DESCRIPTION
**Pull request by rnc**
…d typing.

The reason to switch to `subprocess.run` (https://docs.python.org/3/library/subprocess.html) is: 
> The recommended approach to invoking subprocesses is to use the [run()](https://docs.python.org/3/library/subprocess.html#subprocess.run) function for all use cases it can handle.

### CODE REVIEW

**Comment by jmtd** [comment]
Tested: running behave tests still works;

**Comment by jmtd** [comment]
Problem using podman build back-end:

```
🍊cekit --descriptor ubi8-openjdk-17-runtime.yaml build podman
2022-07-07 15:54:49,508 cli.py:419        WARNING You are running unreleased development version of CEKit, use it only at your own risk!
2022-07-07 15:54:49,516 tools.py:429        INFO  You are running on known platform: Red Hat Enterprise Linux 8.6 (Ootpa)
2022-07-07 15:54:49,517 tools.py:584        WARNING The certifi library (https://certifi.io/) was found, depending on the operating system configuration this may result in certificate validation issues
2022-07-07 15:54:49,517 tools.py:588        WARNING Certificate Authority (CA) bundle in use: '/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/certifi/cacert.pem'
/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/spnego/_ntlm_raw/crypto.py:22: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
2022-07-07 15:54:49,729 builder.py:83         INFO  Generating files for podman engine
2022-07-07 15:54:49,729 base.py:84         INFO  Initializing image descriptor...
2022-07-07 15:54:49,738 resource.py:161        WARNING No value found for 'name' in '{"dest": "/tmp/artifacts/", "path": "modules"}' artifact; using auto-generated value of 'modules'
2022-07-07 15:54:49,744 resource.py:207        INFO  Copying resource 'modules'...
2022-07-07 15:54:50,012 docker.py:21         INFO  Handling artifacts for docker...
2022-07-07 15:54:50,017 base.py:354        INFO  Rendering Dockerfile...
2022-07-07 15:54:50,071 base.py:401        INFO  Rendering help.md page from template /home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/generator/../templates/help.jinja
2022-07-07 15:54:50,085 podman.py:48         INFO  Building container image...
Traceback (most recent call last):
  File "/home/jon/cekit/SUBPROCESS/bin/cekit", line 8, in <module>
    sys.exit(cli())
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/cli.py", line 222, in build_podman
    run_build(ctx, "podman")
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/cli.py", line 395, in run_build
    run_command(ctx, builder_impl)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/cli.py", line 359, in run_command
    Cekit(params).run(clazz)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/cli.py", line 461, in run
    command.execute()
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/builder.py", line 73, in execute
    self.run()
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/builders/podman.py", line 52, in run
    run_wrapper(cmd, False, f"Could not run podman {cmd}")
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/tools.py", line 340, in run_wrapper
    cmd, capture_output=capture_output, check=check, text=True
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Comment by jmtd** [comment]
Problem doing an OSBS scratch build. Same sources/ref as above. I'm about to check which Python version I have in my virtualenv for this test

```
🍊cekit --redhat --descriptor ubi8-openjdk-17-runtime.yaml build --overrides-file redhat/ubi8-openjdk-17-runtime.yaml osbs
2022-07-07 15:57:15,652 cli.py:419        WARNING You are running unreleased development version of CEKit, use it only at your own risk!
2022-07-07 15:57:15,659 tools.py:429        INFO  You are running on known platform: Red Hat Enterprise Linux 8.6 (Ootpa)
2022-07-07 15:57:15,660 tools.py:584        WARNING The certifi library (https://certifi.io/) was found, depending on the operating system configuration this may result in certificate validation issues
2022-07-07 15:57:15,660 tools.py:588        WARNING Certificate Authority (CA) bundle in use: '/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/certifi/cacert.pem'
/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/spnego/_ntlm_raw/crypto.py:22: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
2022-07-07 15:57:15,871 builder.py:87         INFO  Generating files for OSBS engine
2022-07-07 15:57:15,875 base.py:84         INFO  Initializing image descriptor...
2022-07-07 15:57:15,884 resource.py:161        WARNING No value found for 'name' in '{"dest": "/tmp/artifacts/", "path": "modules"}' artifact; using auto-generated value of 'modules'
2022-07-07 15:57:15,894 resource.py:207        INFO  Copying resource 'modules'...
2022-07-07 15:57:16,152 osbs.py:100        INFO  Handling artifacts for OSBS...
2022-07-07 15:57:16,152 base.py:424        WARNING The image has ContentSets repositories specified, all other repositories are removed!
2022-07-07 15:57:16,159 base.py:354        INFO  Rendering Dockerfile...
2022-07-07 15:57:16,213 base.py:401        INFO  Rendering help.md page from template /home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/generator/../templates/help.jinja
Traceback (most recent call last):
  File "/home/jon/cekit/SUBPROCESS/bin/cekit", line 8, in <module>
    sys.exit(cli())
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/cli.py", line 266, in build_osbs
    run_build(ctx, "osbs")
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/cli.py", line 395, in run_build
    run_command(ctx, builder_impl)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/cli.py", line 359, in run_command
    Cekit(params).run(clazz)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/cli.py", line 461, in run
    command.execute()
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/builder.py", line 72, in execute
    self.before_build()
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/builders/osbs.py", line 83, in before_build
    self._prepare_dist_git()
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/builders/osbs.py", line 155, in _prepare_dist_git
    self.params.assume_yes,
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/builders/osbs.py", line 394, in __init__
    ) = DistGit.repo_info(source)
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/builders/osbs.py", line 363, in repo_info
    run_wrapper(["git", "rev-parse", "--is-inside-work-tree"], True).stdout
  File "/home/jon/cekit/SUBPROCESS/lib/python3.6/site-packages/cekit/tools.py", line 340, in run_wrapper
    cmd, capture_output=capture_output, check=check, text=True
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Comment by jmtd** [comment]
Ah of course, [Python 3.6 is deprecated](https://github.com/cekit/cekit/pull/788). At some point we should have some user-facing documentation about minimum supported Python version.

**Comment by jmtd** [comment]
Another weird issue doing OSBS build.

For reference, Cekit 4.1.1/3.6.8, for reference:

```
🍊cekit --redhat --descriptor ubi8-openjdk-8-runtime.yaml build --overrides-file redhat/ubi8-openjdk-8-runtime.yaml --overrides-file dev/ubi8-openjdk-8-runtime.yaml osbs
2022-07-07 16:14:04,868 tools.py:348        INFO  You are running on known platform: Red Hat Enterprise Linux 8.6 (Ootpa)
2022-07-07 16:14:04,869 tools.py:503        WARNING The certifi library (https://certifi.io/) was found, depending on the operating system configuration this may result in certificate validation issues
2022-07-07 16:14:04,869 tools.py:507        WARNING Certificate Authority (CA) bundle in use: '/home/jon/cekit/4.1.1/lib/python3.6/site-packages/certifi/cacert.pem'
/home/jon/cekit/4.1.1/lib/python3.6/site-packages/spnego/_ntlm_raw/crypto.py:22: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
2022-07-07 16:14:05,041 builder.py:87         INFO  Generating files for OSBS engine
2022-07-07 16:14:05,047 base.py:86         INFO  Initializing image descriptor...
2022-07-07 16:14:05,056 resource.py:162        WARNING No value found for 'name' in '{"dest": "/tmp/artifacts/", "path": "modules"}' artifact; using auto-generated value of 'modules'
2022-07-07 16:14:05,068 resource.py:208        INFO  Copying resource 'modules'...
2022-07-07 16:14:05,325 osbs.py:104        INFO  Handling artifacts for OSBS...
2022-07-07 16:14:05,325 base.py:422        WARNING The image has ContentSets repositories specified, all other repositories are removed!
2022-07-07 16:14:05,333 base.py:352        INFO  Rendering Dockerfile...
2022-07-07 16:14:05,387 base.py:399        INFO  Rendering help.md page from template /home/jon/cekit/4.1.1/lib/python3.6/site-packages/cekit/generator/../templates/help.jinja
2022-07-07 16:14:05,474 osbs.py:428        INFO  Fetching latest changes in repo containers/openjdk...
Switched to branch 'private-jdowland-openjdk-8-runtime-ubi8'
Your branch is up to date with 'origin/private-jdowland-openjdk-8-runtime-ubi8'.
HEAD is now at 9beb25d Sync with openjdk, commit 60990882cadddce6df02c8a8acff242033154514
Removing gating.yaml~
2022-07-07 16:14:10,129 osbs.py:478        INFO  Removing old 'repos' directory
2022-07-07 16:14:10,129 osbs.py:478        INFO  Removing old 'modules' directory
2022-07-07 16:14:10,290 osbs.py:263        INFO  Updating lookaside cache...
2022-07-07 16:14:10,300 osbs.py:176        INFO  No changes made to the code, committing skipped
2022-07-07 16:14:10,332 osbs.py:339        INFO  About to execute '/usr/bin/brew call --python buildContainer --kwargs {'src': 'git://pkgs.devel.redhat.com/containers/openjdk#9beb25d32f6ea2fe669b85e5a92696a4e641dd49', 'target': 'openjdk-8-runtime-ubi8-containers-candidate', 'opts': {'scratch': True, 'git_branch': 'private-jdowland-openjdk-8-runtime-ubi8', 'yum_repourls': []}}'.
Do you want to build the image in OSBS? [y/N]: n
2022-07-07 16:14:26,371 cli.py:462        INFO  Finished!
```

With this branch and 3.9.7:

```
🍊cekit --redhat --descriptor ubi8-openjdk-8-runtime.yaml build --overrides-file redhat/ubi8-openjdk-8-runtime.yaml --overrides-file dev/ubi8-openjdk-8-runtime.yaml osbs
2022-07-07 16:15:18,290 cli.py:418        WARNING You are running unreleased development version of CEKit, use it only at your own risk!
2022-07-07 16:15:18,296 tools.py:427        INFO  You are running on known platform: Red Hat Enterprise Linux 8.6 (Ootpa)
2022-07-07 16:15:18,297 tools.py:581        WARNING The certifi library (https://certifi.io/) was found, depending on the operating system configuration this may result in certificate validation issues
2022-07-07 16:15:18,297 tools.py:587        WARNING Certificate Authority (CA) bundle in use: '/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/certifi/cacert.pem'
2022-07-07 16:15:18,430 builder.py:87         INFO  Generating files for OSBS engine
2022-07-07 16:15:18,435 base.py:84         INFO  Initializing image descriptor...
2022-07-07 16:15:18,443 resource.py:159        WARNING No value found for 'name' in '{"dest": "/tmp/artifacts/", "path": "modules"}' artifact; using auto-generated value of 'modules'
2022-07-07 16:15:18,450 resource.py:207        INFO  Copying resource 'modules'...
2022-07-07 16:15:18,678 osbs.py:100        INFO  Handling artifacts for OSBS...
2022-07-07 16:15:18,678 base.py:423        WARNING The image has ContentSets repositories specified, all other repositories are removed!
2022-07-07 16:15:18,685 base.py:354        INFO  Rendering Dockerfile...
2022-07-07 16:15:18,731 base.py:400        INFO  Rendering help.md page from template /home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/cekit/generator/../templates/help.jinja
Traceback (most recent call last):
  File "/home/jon/cekit/SUBPROCESS-3.9/bin/cekit", line 8, in <module>
    sys.exit(cli())
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/cekit/cli.py", line 266, in build_osbs
    run_build(ctx, "osbs")
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/cekit/cli.py", line 395, in run_build
    run_command(ctx, builder_impl)
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/cekit/cli.py", line 359, in run_command
    Cekit(params).run(clazz)
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/cekit/cli.py", line 461, in run
    command.execute()
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/cekit/builder.py", line 72, in execute
    self.before_build()
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/cekit/builders/osbs.py", line 83, in before_build
    self._prepare_dist_git()
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/cekit/builders/osbs.py", line 149, in _prepare_dist_git
    self.dist_git = DistGit(
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/cekit/builders/osbs.py", line 394, in __init__
    ) = DistGit.repo_info(source)
  File "/home/jon/cekit/SUBPROCESS-3.9/lib/python3.9/site-packages/cekit/builders/osbs.py", line 366, in repo_info
    raise Exception(
Exception: Directory target doesn't seem to be a git repository. Please make sure you specified correct path.
```

**Comment by jmtd** [comment]
For completion's sake: this branch, Python 3.9.7, `cekit --descriptor ubi8-openjdk-17-runtime.yaml build podman` works fine

**Comment by rnc** [comment]
> Re-testing on RHEL8 with Python 3.9.7 (via `python39-3.9.7-1.module+el8.6.0+12577+62b8d0a1.x86_64`), the podman build works but I get the following error for OSBS builds:
> 

Thanks, I've found a problem (a missing `strip()` during the porting) and will submit an update and a new test.

**Comment by jmtd** [comment]
Retested, all good 👍🏼

**Review by jmtd — APPROVED** [review]
LGTM

**Pull request merged**
