### PR TITLE
If we install pkgs in discrete steps now, we probably need to clean the pkg cache every time

### PR DESCRIPTION
**Pull request by luck3y**

### CODE REVIEW

**Comment by luck3y** [comment]
@goldmann Note this allows my microdnf build to complete, but the image is quite large at the end (>1gb).

So this isn't the whole story here.

**Comment by goldmann** [comment]
We do this on purpose.

We create cache at the beginning of the flow and clear the cache at the end to make the build faster. In other case, the repository cache will be rebuilt on every package manager execution which will significantly slower the execution.

I don't think we gain much more by clearing the cache after every execution.

**Comment by goldmann** [comment]
@errantepiphany @jmtd any opinions here?

**Comment by luck3y** [comment]
@goldmann Based on email discussions, we can probably close this in favor of a pkg manager / OS fix I think.

**Comment by goldmann** [comment]
Sure, I'm happy with this.

**Comment by errantepiphany** [comment]
@goldmann No strong opinion. Will default to your guys' decision, thanks. :)

**Pull request closed without merging**
