### PR TITLE
fix small typo in cli.py

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by goldmann** [comment]
I approved this, but it looks like it targets master. we do not add any commits to master, but instead we work on develop for the next Cekit version. Only bugfixes are backported to master.

**Comment by goldmann** [comment]
I tried to change the base to develop, but it resulted in fairly big mess, so I reverted this. Can you please open this PR against develop?

**Comment by vorburger** [comment]
> Can you please open this PR against develop?

done

**Comment by goldmann** [comment]
Thanks!

**Pull request merged**
