### PR TITLE
Build documentation on CI too

### LINKED ISSUE #426: Enhance CI to build docs
As part of CI build (for PR) we should also build documentation. Files should be saved as artifacts to check them later. Additionally this will ensure that documentation is still building.

### PR DESCRIPTION
**Pull request by goldmann**
Fixes #426

### CODE REVIEW

**Comment by goldmann** [comment]
You can even see how it is run in the checks above, or result of the build as saved artifacts here: https://994-102005331-gh.circle-artifacts.com/0/home/circleci/project/docs/_build/html/index.html

**Comment by rnc** [comment]
I see this PR now has the docs-build link. How do I find from that link the link you gave to the docs ( https://994-102005331-gh.circle-artifacts.com/0/home/circleci/project/docs/_build/html/index.html ) ?

**Comment by goldmann** [comment]
You click on the link to Circle CI for the docs-build, then you go to the "Artifacts" tab.

**Comment by rnc** [comment]
I don't have an artifacts tab!

**Comment by goldmann** [comment]
Yah, I can confirm it by viewing in a incognito window. I'll check if I can change it.

**Comment by goldmann** [comment]
Do you have a CircleCI account? If yes, can you try to log in and try again?

**Comment by rnc** [comment]
Ok making an account allows me to see : 

```
 Container 0

    home/
        circleci/
            project/
                docs/
                    _build/
                        doctrees/
                        html/
```

in the artifacts section.

**Pull request merged**
